eclub/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^items/', include('items.urls')),
    url(r'^', include('items.urls')),
]

items/urls.py
#this files tells which function/class to call form views.py when the user enters one of the following specified urls
from django.conf.urls import url
from . import views

app_name = 'items' #this app name helps to distinguish eg index.html files of different apps while referencing utls

urlpatterns = [
    # login page
    #homepage showing links to forms to issue items, return issued items, list of location of boxes
    #and list of items issued by the given user

    #/items/
    url(r'^$', views.myIssues, name='index'),
    #/items/register
    url(r'^register/$', views.UserFormView.as_view(), name='register'),
    #/items/myIssues
    url(r'^myIssues/$', views.myIssues, name='myIssues'),
    #/items/change_location
    url(r'^change_location/$', views.change_location, name='change_location'),
    #/items/boxes_list
    url(r'^boxes_list/$', views.boxes_list, name='boxes_list'),
    # /items/create_issue
    url(r'^create_issue/$', views.create_issue, name='create_issue'),
    # /items/create_return
    url(r'^(?P<issue_id>[0-9]+)/create_return/$', views.create_return, name='create_return'),

    #/items/login_user
    url(r'^login_user/$', views.login_user, name='login_user'),
    #/items/logout_user
    url(r'^logout_user/$', views.logout_user, name='logout_user'),
    # /home/<box_id>/
    url(r'^(?P<box_id>[0-9]+)/$', views.issues_by_box, name="issues_by_box"),
]


items/models.py
from django.db import models
from django.contrib.auth.models import User

class Box(models.Model):
    number = models.CharField(max_length=500)
    item = models.CharField(max_length=500)
    quantity_total = models.IntegerField()
    quantity_left = models.IntegerField()
    location = models.CharField(max_length=1000)

    def __str__(self):
        return self.item

class Issued(models.Model):
    box = models.ForeignKey(Box, on_delete=models.CASCADE)
    quantity_issued = models.IntegerField()
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    returned = models.BooleanField(default=False)
    return_number = models.CharField(max_length=500, default='')


items/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Box, Issued

#this file is for tweaking the default UserForm to remove useless fiels and add new forms.

class UserForm(forms.ModelForm):
    #this tells django is password is a password field
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        #user model already exists in django
        model = User
        #use only given fields and omit useless fields like DOB, first name etc.
        fields = ['username', 'password']

class IssuedForm(forms.ModelForm):

    class Meta:
        model = Issued
        fields = ['box', 'quantity_issued']

class LocationForm(forms.ModelForm):

    class Meta:
        model = Box
        fields = ['number', 'location']

class ReturnIssue(forms.ModelForm):

    class Meta:
        model = Issued
        fields = ['return_number']

items/views.py
from .models import Box, Issued
from django.shortcuts import render, get_object_or_404
from django.contrib.auth import authenticate, login, logout
from .forms import UserForm, IssuedForm, ReturnIssue, LocationForm
from django.views.generic import View


# Create your views here.

#list of boxes with location and items left in each box
def boxes_list(request):
    if not request.user.is_authenticated:
        return render(request, 'items/login.html')
    else:
        boxes = Box.objects.all()
        return render(request, 'items/box_list.html', {'boxes': boxes})

#list showing issues of a user
def myIssues(request):
    # if user is not a registered user, redirect them to login page
    if not request.user.is_authenticated:
        return render(request, 'items/login.html')
    else:
        user = request.user
        issues = Issued.objects.filter(user=request.user)
        return render(request, 'items/myIssues.html', {'user': user, 'issues': issues})

#list showing issues in a box (for admin)
def issues_by_box(request, box_id):
    if not request.user.is_authenticated:
        return render(request, 'items/login.html')
    else:
        user = request.user
        box = get_object_or_404(Box, pk=box_id)
        issues = Issued.objects.filter(box=box)
        return render(request, 'items/issues_by_box.html', {'user': user, 'issues': issues, 'box': box})

def create_issue(request):
    #use DiscussionFormIndex class from forms.py
    if not request.user.is_authenticated:
        return render(request, 'items/login.html')
    else:
        form = IssuedForm(request.POST or None, request.FILES or None)
        if form.is_valid():
            #do not save to database now
            issue = form.save(commit=False)
            issue.user = request.user
            if issue.quantity_issued > issue.box.quantity_left: #if a picture is uploaded
                return render(request, 'items/issue_form.html', {'form': form, 'error_message': 'Quantity asked is more than the quantity of item available'})
            #save to database
            issue.box.quantity_left = issue.box.quantity_left - issue.quantity_issued
            issue.save()
            issue.box.save()

            return render(request, 'items/index.html', {})
        return render(request, 'items/issue_form.html', {'form': form})

def change_location(request):
    #use DiscussionFormIndex class from forms.py
    if not request.user.is_authenticated:
        return render(request, 'items/login.html')
    else:
        form = LocationForm(request.POST or None, request.FILES or None)
        if form.is_valid():
            #do not save to database now
            issue = form.save(commit=False)
            box = get_object_or_404(Box, number=issue.number)
            box.location = issue.location
            box.save()

            return render(request, 'items/index.html', {})
        return render(request, 'items/issue_form.html', {'form': form})

def create_return(request, issue_id):
    #use DiscussionFormIndex class from forms.py
    if not request.user.is_authenticated:
        return render(request, 'items/login.html')
    else:
        form = ReturnIssue(request.POST or None, request.FILES or None)
        issued = get_object_or_404(Issued, pk=issue_id)
        if form.is_valid():
            #do not save to database now
            issue = form.save(commit=False)
            if issue.return_number != issued.box.number: #if a picture is uploaded
                return render(request, 'items/return_form.html', {'form': form, 'error_message': 'Box number mismatch. Please put the item in the correct box.'})
            #save to database
            issued.returned = True
            issued.box.quantity_left = issued.box.quantity_left + issued.quantity_issued
            issued.return_number = issue.return_number
            issued.save()
            issued.box.save()

            return render(request, 'items/index.html', {})
        return render(request, 'items/issue_form.html', {'form': form})



def logout_user(request):
    logout(request)
    form = UserForm(request.POST or None)
    return render(request, 'items/login.html', {"form": form})

#logging in a user
def login_user(request):
    #if user is already logged in, return them to homepage
    if request.user.is_authenticated:
        return render(request, 'items/index.html', {'error_message': 'You are already logged in! Click on the Oraculi button on the top left corner of screen'})
    #process form data
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        #if user exists
        if user is not None:
            #if user is not suspended
            if user.is_active:
                #login funtion is already in request
                login(request, user)
                return render(request, 'items/index.html', {})
            else:
                return render(request, 'items/login.html', {'error_message': 'Your account has been disabled'})
        else:
            return render(request, 'items/login.html', {'error_message': 'Invalid login'})
    return render(request, 'items/login.html')

class UserFormView(View):
    #Credits: code structure for this class is adapted from newboston django video tutorials.
    form_class = UserForm
    template_name = 'items/registration_form.html'

    #display blank form
    def get(self, request):
        form = self.form_class(None)
        return render(request, self.template_name, {'form': form})

    #process form data
    def post(self, request):
        form = self.form_class(request.POST)

        if form.is_valid():
            user = form.save(commit=False)
            #cleaned(normalized) data
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user.set_password(password)
            #add user to the database
            user.save()

            #returns user objects if credentials are correct
            user = authenticate(username=username, password=password)

            if user is not None:
                #django gives admin power to suspend users. This option checks if the user is not suspended.
                if user.is_active:
                    login(request, user)
                    user = request.user
                    issues = Issued.objects.filter(user=request.user)
                    return render(request, 'items/myIssues.html', {'user': user, 'issues': issues})
        return render(request, self.template_name, {'form': form})



















items/templates/items/base.html
<!--this html file is used by all other html files of the website and contains navbar-->
<!--this webpage template used from newboston django tutorials-->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}E-Club IITK{%endblock%}</title>
    <!-- loads static files -->
    {%load staticfiles%}
    <link rel="shortcut icon" type="image/png" href="{%  static 'favicon.ico' %}"/>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
     <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <!-- jQuery library -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <!-- Latest compiled JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'home/style.css' %}" />
</head>
<body>
        <!-- navbar -->
        <nav class="navbar navbar-inverse">
        <div class="container-fluid">

            <!--logo + buttons-->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toogle="collapse" data-target="#TopNavBar">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{%url 'items:index'%}">{{request.user.username}}</a>
            </div>

            <!-- Items -->
            <div class="collapse navbar-collapse" id="topNavBar">

                <ul class="nav navbar-nav navbar-right">

                    <li class="">
                        <a href="{% url 'items:myIssues' %}">
                            <span class=" 	glyphicon glyphicon-th-list" aria-hidden="true"></span>&nbsp; Items Issued
                        </a>
                    </li>
                    <li class="">
                        <a href="{% url 'items:create_issue' %}">
                            <span class=" 	glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp; Issue
                        </a>
                    </li>
                    <li class="">
                        <a href="{% url 'items:boxes_list' %}">
                            <span class="glyphicon glyphicon-list-alt" aria-hidden="true"></span>&nbsp; Location of boxes
                        </a>
                    </li>
                    <li class="">
                        <a href="{% url 'items:change_location' %}">
                            <span class=" 	glyphicon glyphicon-transfer" aria-hidden="true"></span>&nbsp; Change location
                        </a>
                    </li>

                    <li class="">
                        <a href="{% url 'items:logout_user' %}">
                            <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp;Log Out
                        </a>
                    </li>
                </ul>
            </div>

        </div>
    </nav>

    <!-- Block of html code for the rest of the page under navbar -->
{% block body %}
{%endblock%}

</body>
</html>

items/templates/items/box_list.html
{%extends 'items/base.html'%}
{% block title %}boxes list{%endblock%}
{% block body %}

<div class="container-fluid songs-container">

    <div class="row">
        <div class="col-sm-12 col-md-12">

            <div class="panel panel-default">
                <div class="panel-body">

                    <h3>Boxes list</h3>

                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}

                    <table class="table">
                        <thead>
                            <tr>
                                <th></th>
                                <th>Item</th>
                                <th>Location</th>
                                <th>Total quantity</th>
                                <th>Quantity remaining</th>
                            </tr>
                        </thead>

                        {%for d in boxes %}
                        <tbody>
                            <tr>
                                <th>{{ forloop.counter }}.</th>
                                <td>{{d.item}}</td>
                                <td>{{d.location}}</td>
                                <td>{{d.quantity_total}}</td>
                                <td>{{d.quantity_left}}</td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>

                </div>
            </div>

        </div>

    </div>

</div>

{% endblock %}

items/templates/items/form_template.html
{%for field in form%}
    <div class="form-group">
       <!-- <div class="col-sm-offset-2 col-sm-10">
            <span class="text-danger sml">{{ field.errors }}</span>
        </div> -->
        <label class="">{{ field.label_tag }}</label>
        <div class="">{{ field }}</div>
    </div>
{%endfor%}

items/templates/items/index.html
{%extends 'items/base.html'%}
{% block title %}Index{%endblock%}
{% block body %}

<h1>Use navigation bar to navigate.</h1>

{% endblock %}

items/templates/items/issue_form.html
{%extends 'items/base.html'%}
{% block title %}Issue Item{%endblock%}
{% block body %}

    {%if error_message%}
                    <p><strong>{{error_message}}</strong></p> <!-- error_message is a variable -->
                    {%endif%}

                    <form class="" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {%include 'items/form_template.html'%}
                        <div class="">
                            <div class=" ">
                                <button type="submit" class="">Submit</button>
                            </div>
                        </div>
                    </form>
{% endblock %}

items/templates/items/issues_by_box.html
{%extends 'items/base.html'%}
{% block title %}My Discussions{%endblock%}
{% block body %}

    <p>issues_by_box</p>
{% endblock %}

items/templates/items/login.html
<!--credits: webpage template used from newboston django tutorials-->

<div class="container-fluid">

    <div class="row">

        <!-- left info -->
        <div class="col-sm-12 col-md-6">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Log In</h3>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="{% url 'items:login_user'%}" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="form-group">
                            <label class="control-label col-sm-2" for="id_username">
                                Username:
                            </label>
                            <div class="col-sm-10">
                                <input id="id_username" maxlength="30" name="username" type="text">
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-sm-2" for="id_password">
                                Password:
                            </label>
                            <div class="col-sm-10">
                                <input id="id_password" maxlength="30" name="password" type="password">
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
                <div class="panel-footer">
                    Don't have an account? <a href="{% url 'items:register' %}">Click here</a> to register.
                </div>
            </div>
        </div>
    </div>

</div>

items/templates/items/myIssues.html
{%extends 'items/base.html'%}
{% block title %}My Issues{%endblock%}
{% block body %}

<div class="container-fluid songs-container">

    <div class="row">
        <div class="col-sm-12 col-md-12">

            <div class="panel panel-default">
                <div class="panel-body">

                    <h3>Items issued by {{user.username}}</h3>

                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}

                    <table class="table">
                        <thead>
                            <tr>
                                <th></th>
                                <th>Item</th>
                                <th>Location</th>
                                <th>Quantity Issued</th>
                                <th>Return</th>
                            </tr>
                        </thead>

                        {%for d in issues %}
                        <tbody>
                            <tr>
                                <th>{{ forloop.counter }}.</th>
                                <td>{{d.box.item}}</td>
                                <td>{{d.box.location}}</td>
                                <td>{{d.quantity_issued}}</td>
                                <td>{%if d.returned is False%}<a href="{% url 'items:create_return' d.id%}">Return</a>{%else%}Item returned{%endif%}</td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>

                </div>
            </div>

        </div>

    </div>

</div>

{% endblock %}

items/templates/items/registration_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Register</title>
</head>
<body>
    <h3>Register</h3>
                     {%if error_message%}
                    <p><strong>{{error_message}}</strong></p> <!-- error_message is a variable -->
                    {%endif%}

                    <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {%include 'items/form_template.html'%}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
</body>
</html>

items/templates/items/return_form.html
{%extends 'items/base.html'%}
{% block title %}Return{%endblock%}
{% block body %}
            {%if error_message%}
                    <p><strong>{{error_message}}</strong></p> <!-- error_message is a variable -->
                    {%endif%}

                    <form class="" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {%include 'items/form_template.html'%}
                        <div class="">
                            <div class=" ">
                                <button type="submit" class="">Submit</button>
                            </div>
                        </div>
                    </form>

{% endblock %}